### PR TITLE
Add indexes constraints

### PR DESCRIPTION
**Pull request by AlexicaWright**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-data-importer-27.surge.sh

New pages:
- [Indexes and constraints](https://neo4j-docs-data-importer-27.surge.sh/data-importer/1.0/indexes-constraints)

Updated pages:
- [Mapping](https://neo4j-docs-data-importer-27.surge.sh/data-importer/1.0/mapping)
- [Overview](https://neo4j-docs-data-importer-27.surge.sh/data-importer/1.0/overview)

**Review by xiaojieyang — APPROVED** [review]

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-data-importer-27.surge.sh

New pages:
- [Indexes and constraints](https://neo4j-docs-data-importer-27.surge.sh/data-importer/1.0/indexes-constraints)

Updated pages:
- [Neo4j Data Importer](https://neo4j-docs-data-importer-27.surge.sh/data-importer/1.0)
- [Mapping](https://neo4j-docs-data-importer-27.surge.sh/data-importer/1.0/mapping)
- [Overview](https://neo4j-docs-data-importer-27.surge.sh/data-importer/1.0/overview)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-data-importer-27.surge.sh

New pages:
- [Indexes and constraints](https://neo4j-docs-data-importer-27.surge.sh/data-importer/1.0/indexes-constraints)

Updated pages:
- [Neo4j Data Importer](https://neo4j-docs-data-importer-27.surge.sh/data-importer/1.0)
- [Mapping](https://neo4j-docs-data-importer-27.surge.sh/data-importer/1.0/mapping)
- [Overview](https://neo4j-docs-data-importer-27.surge.sh/data-importer/1.0/overview)

**Review by eijawerner — APPROVED** [review]
⭐

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-data-importer-27.surge.sh

New pages:
- [Indexes and constraints](https://neo4j-docs-data-importer-27.surge.sh/data-importer/1.0/indexes-constraints)

Updated pages:
- [Neo4j Data Importer](https://neo4j-docs-data-importer-27.surge.sh/data-importer/1.0)
- [Mapping](https://neo4j-docs-data-importer-27.surge.sh/data-importer/1.0/mapping)
- [Overview](https://neo4j-docs-data-importer-27.surge.sh/data-importer/1.0/overview)

**Pull request merged**
